In [1]:
import os
os.chdir("D:\Work flow")

In [2]:
import pandas as pd
data = pd.read_csv("#1china.csv")

In [3]:
data.head()

Country Province/State      Last Update  Confirmed  Deaths  Recovered  nDate
0   China   Heilongjiang  1/22/2020 12:00          0       0          0     22
1   China          Hunan  1/22/2020 12:00          4       0          0     22
2   China         Shanxi  1/22/2020 12:00          1       0          0     22
3   China        Ningxia  1/22/2020 12:00          1       0          0     22
4   China       Xinjiang  1/22/2020 12:00          0       0          0     22

In [4]:
data = data.sort_values(by=['Province/State'])

In [5]:
data = data.drop("Country",axis = 1)

In [6]:
data.head()

Province/State      Last Update  Confirmed  Deaths  Recovered  nDate
64           Anhui  1/25/2020 12:00         60       0          0     25
278          Anhui    2/2/2020 1:33        340       0          5     33
277          Anhui  1/30/2020 21:30        237       0          3     30
276          Anhui  1/31/2020 19:00        237       0          3     31
275          Anhui  1/29/2020 21:00        200       0          2     29

In [7]:
data = data.sort_values(by=['nDate'])

In [8]:
data.head()

Province/State     Last Update  Confirmed  Deaths  Recovered  nDate
351          Hubei  1/2/2020 23:33       9074     294        215      2
292      Chongqing  1/2/2020 23:43        262       1          3      2
205         Shanxi  1/2/2020 23:33         56       0          1      2
156         Yunnan  1/2/2020 15:53         93       0          2      2
130          Tibet   1/2/2020 1:52          1       0          0      2

In [9]:
data = data.set_index(["nDate"])

In [10]:
data.head()

Province/State     Last Update  Confirmed  Deaths  Recovered
nDate                                                             
2              Hubei  1/2/2020 23:33       9074     294        215
2          Chongqing  1/2/2020 23:43        262       1          3
2             Shanxi  1/2/2020 23:33         56       0          1
2             Yunnan  1/2/2020 15:53         93       0          2
2              Tibet   1/2/2020 1:52          1       0          0

In [11]:
data = data.sum(level = "nDate")

In [12]:
data

Confirmed  Deaths  Recovered
nDate                              
2           9600     295        222
22           549       0          0
23           639      18         30
24           916      26         36
25          1979      56         49
26          2737      80         51
27          4409     107         60
28          5970     132        104
29          7678     170        127
30          9658     213        179
31         11221     259        242
32             1       0          0
33         17220     364        434
34          1142       3         35
35         19257     422        600
36          4669       6        153

In [13]:
#data.to_csv("##1china.csv")

In [14]:
data = data.drop([2,32,34,36],axis = 0)

In [15]:
data

Confirmed  Deaths  Recovered
nDate                              
22           549       0          0
23           639      18         30
24           916      26         36
25          1979      56         49
26          2737      80         51
27          4409     107         60
28          5970     132        104
29          7678     170        127
30          9658     213        179
31         11221     259        242
33         17220     364        434
35         19257     422        600

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
reg = LinearRegression()

In [18]:
data  = data.reset_index()
#reg.fit(data.nDate , data.Confirmed)

In [19]:
reg.fit(data[['nDate']] , data[['Confirmed']])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [20]:
reg.predict(37)

array([[21182.66058906]])

In [21]:
reg.predict(38)

array([[22731.8401122]])

In [98]:
def GD(x,y):
    m = 0
    b = 0
    n = 1000
    learn = 0.0015
    k = len(x)
    for i in range(n):
        y_predicted = m*x + b
        error =     (1/k)    *      sum((y-y_predicted)**2)
        error_dm =  (-2/k)   *      sum(x*(y-y_predicted))
        error_db =  (-2/k)   *      sum(y-y_predicted)
        m= m - learn*error_dm
        b= b - learn*error_db
        return error , m ,b

In [99]:
error , m , b = GD(data['nDate'] , data['Confirmed'])

In [100]:
def pred(m,b,x):
    return m*x+b

In [101]:
pred(m,b,37)

23683.048

In [118]:
import numpy as np

theta,resd,rank,s = np.linalg.lstsq(data[['nDate']],data[['Confirmed']],rcond=None)

In [119]:
theta,resd

(array([[271.59008387]]), array([3.18780012e+08]))

In [120]:
271.59008387*37+3.18780012e+08

318790060.8331032